const DefaultGameState = {
  health: {
    current: 0,
    maximum: 0,
  },
  position: {
    x: 0,
    y: 0,
    z: 0,
  },
  magic: 0,
  deaths: 0,
  rupees: 0,
  frozen: false,
  inventory: [],
  songs: {
    zelda: false,
    epona: false,
    saria: false,
    sun: false,
    time: false,
    storms: false,
    minuet: false,
    bolero: false,
    serenade: false,
    nocturne: false,
    requiem: false,
    prelude: false,
  },
  medallions: {
    light: false,
    forest: false,
    fire: false,
    water: false,
    shadow: false,
    spirit: false,
  },
  stones: {
    kokiri: false,
    goron: false,
    zora: false,
  },
  equipment: {
    swords: {
      kokiri: false,
      master: false,
      biggorons: false,
      knife: false,
      broken: false,
    },
    shields: {
      deku: false,
      hylian: false,
      mirror: false,
    },
    boots: {
      kokiri: false,
      iron: false,
      hover: false,
    },
    tunics: {
      kokiri: false,
      goron: false,
      zora: false,
    },
  },
  progressives: {
    wallet: 0,
    scale: 0,
    magic: 0,
    sticks: 0,
    nuts: 0,
    bombs: 0,
    bullets: 0,
    quiver: 0,
  },
  counts: {
    sticks: 0,
    nuts: 0,
    bombs: 0,
    arrows: 0,
    bullets: 0,
    bombchus: 0,
    beans: 0,
  },
  other: {
    skulltulaTokens: 0,
    stoneOfAgony: false,
    gerudoCard: false,
    heartPieces: 0,
    triforcePieces: 0,
  },
};

export default DefaultGameState;
