/* eslint-disable no-unused-vars */
enum ItemValues {
  DekuSticks = 0x0,
  DekuNuts,
  Bombs,
  Bow,
  FireArrows,
  DinsFire,
  Slingshot,
  FairyOcarina,
  OcarinaOfTime,
  Bombchus,
  Hookshot,
  Longshot,
  IceArrows,
  FaroresWind,
  Boomerang,
  LensOfTruth,
  MagicBeans,
  MegatonHammer,
  LightArrows,
  NayrusLove,
  BottleEmpty,
  BottleRedPotion,
  BottleGreenPotion,
  BottleBluePotion,
  BottleFairy,
  BottleFish,
  BottleMilk,
  BottleRutosLetter,
  BottleBlueFire,
  BottleBugs,
  BottleBigPoe,
  BottleHalfMilk,
  BottlePoe,
  WeirdEgg,
  Cucco,
  ZeldasLetter,
  KeatonMask,
  SkullMask,
  SpookyMask,
  BunnyHood,
  GoronMask,
  ZoraMask,
  GerudoMask,
  MaskOfTruth,
  SoldOut,
  PocketEgg,
  PocketCucco,
  Cojiro,
  OddMushroom,
  OddPoultice,
  PoachersSaw,
  BrokenGoronsSword,
  Prescription,
  EyeballFrog,
  WorldsFinestEyeDrops,
  ClaimCheck,
  Empty = 0xFF
}

export default ItemValues;
