import ItemValues from './itemValues';

type Item = {
  codeName: string,
  properName: string,
}
const ItemNames: Map<ItemValues, Item> = new Map([
  [ItemValues.DekuSticks, { codeName: 'stick', properName: 'Deku Sticks' }],
  [ItemValues.DekuNuts, { codeName: 'nut', properName: 'Deku Nuts' }],
  [ItemValues.Bombs, { codeName: 'bomb', properName: 'Bombs' }],
  [ItemValues.Bow, { codeName: 'bow', properName: 'Bow' }],
  [ItemValues.FireArrows, { codeName: 'fire-arrows', properName: 'Fire Arrows' }],
  [ItemValues.DinsFire, { codeName: 'din', properName: "Din's Fire" }],
  [ItemValues.Slingshot, { codeName: 'slingshot', properName: 'Slingshot' }],
  [ItemValues.FairyOcarina, { codeName: 'ocarina-fairy', properName: 'Fairy Ocarina' }],
  [ItemValues.OcarinaOfTime, { codeName: 'ocarina-time', properName: 'Ocarina of Time' }],
  [ItemValues.Bombchus, { codeName: 'bombchu', properName: 'Bombchus' }],
  [ItemValues.Hookshot, { codeName: 'hookshot', properName: 'Hookshot' }],
  [ItemValues.Longshot, { codeName: 'longshot', properName: 'Longshot' }],
  [ItemValues.IceArrows, { codeName: 'ice-arrows', properName: 'Ice Arrows' }],
  [ItemValues.FaroresWind, { codeName: 'farore', properName: "Farore's Wind" }],
  [ItemValues.Boomerang, { codeName: 'boomerang', properName: 'Boomerang' }],
  [ItemValues.LensOfTruth, { codeName: 'lens', properName: 'Lens of Truth' }],
  [ItemValues.MagicBeans, { codeName: 'bean', properName: 'Magic Beans' }],
  [ItemValues.MegatonHammer, { codeName: 'hammer', properName: 'Megaton Hammer' }],
  [ItemValues.LightArrows, { codeName: 'light-arrows', properName: 'Light Arrows' }],
  [ItemValues.NayrusLove, { codeName: 'nayru', properName: "Nayru's Love" }],
  [ItemValues.BottleEmpty, { codeName: 'bottle-empty', properName: 'Empty Bottle' }],
  [ItemValues.BottleRedPotion, { codeName: 'bottle-red', properName: 'Red Potion' }],
  [ItemValues.BottleGreenPotion, { codeName: 'bottle-green', properName: 'Green Potion' }],
  [ItemValues.BottleBluePotion, { codeName: 'bottle-blue', properName: 'Blue Potion' }],
  [ItemValues.BottleFairy, { codeName: 'bottle-fairy', properName: 'Fairy' }],
  [ItemValues.BottleFish, { codeName: 'bottle-fish', properName: 'Fish' }],
  [ItemValues.BottleMilk, { codeName: 'bottle-milk', properName: 'Lon Lon Milk' }],
  [ItemValues.BottleRutosLetter, { codeName: 'bottle-letter', properName: "Ruto's Letter" }],
  [ItemValues.BottleBlueFire, { codeName: 'bottle-fire', properName: 'Blue Fire' }],
  [ItemValues.BottleBugs, { codeName: 'bottle-bugs', properName: 'Bugs' }],
  [ItemValues.BottleBigPoe, { codeName: 'bottle-big-poe', properName: 'Big Poe Soul' }],
  [ItemValues.BottleHalfMilk, { codeName: 'bottle-milk-half', properName: 'Lon Lon Milk (Half)' }],
  [ItemValues.BottlePoe, { codeName: 'bottle-poe', properName: 'Poe Soul' }],
  [ItemValues.WeirdEgg, { codeName: 'weird-egg', properName: 'Weird Egg' }],
  [ItemValues.Cucco, { codeName: 'cucco', properName: 'Cucco' }],
  [ItemValues.ZeldasLetter, { codeName: 'letter', properName: "Zelda's Letter" }],
  [ItemValues.KeatonMask, { codeName: 'mask-keaton', properName: 'Keaton Mask' }],
  [ItemValues.SkullMask, { codeName: 'mask-skull', properName: 'Skull Mask' }],
  [ItemValues.SpookyMask, { codeName: 'mask-spooky', properName: 'Spooky Mask' }],
  [ItemValues.BunnyHood, { codeName: 'mask-bunny', properName: 'Bunny Hood' }],
  [ItemValues.GoronMask, { codeName: 'mask-goron', properName: 'Goron Mask' }],
  [ItemValues.ZoraMask, { codeName: 'mask-zora', properName: 'Zora Mask' }],
  [ItemValues.GerudoMask, { codeName: 'mask-gerudo', properName: 'Gerudo Mask' }],
  [ItemValues.MaskOfTruth, { codeName: 'mask-truth', properName: 'Mask of Truth' }],
  [ItemValues.SoldOut, { codeName: 'sold-out', properName: 'Sold Out' }],
  [ItemValues.PocketEgg, { codeName: 'pocket-egg', properName: 'Pocket Egg' }],
  [ItemValues.PocketCucco, { codeName: 'pocket-cucco', properName: 'Pocket Cucco' }],
  [ItemValues.Cojiro, { codeName: 'cojiro', properName: 'Cojiro' }],
  [ItemValues.OddMushroom, { codeName: 'mushroom', properName: 'Odd Mushroom' }],
  [ItemValues.OddPoultice, { codeName: 'medicine', properName: 'Odd Poultice' }],
  [ItemValues.PoachersSaw, { codeName: 'saw', properName: "Poacher's Saw" }],
  [ItemValues.BrokenGoronsSword, { codeName: 'broken-sword', properName: "Broken Goron's Sword" }],
  [ItemValues.Prescription, { codeName: 'prescription', properName: 'Prescription' }],
  [ItemValues.EyeballFrog, { codeName: 'frog', properName: 'Eyeball Frog' }],
  [ItemValues.WorldsFinestEyeDrops, { codeName: 'eye-drops', properName: "World's Finest Eye Drops" }],
  [ItemValues.ClaimCheck, { codeName: 'claim', properName: 'Claim Check' }],
  [ItemValues.Empty, { codeName: 'empty', properName: 'No Item' }],
]);

export default ItemNames;
